# Generated by Django 5.0.6 on 2024-06-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('porta', models.IntegerField()),
                ('dnp', models.IntegerField()),
                ('range_bi', models.CharField(max_length=10)),
                ('range_ai', models.CharField(max_length=10)),
                ('range_bo', models.CharField(max_length=10)),
                ('faixa_ip_se', models.CharField(max_length=20)),
                ('data_de_criacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
