# Generated by Django 5.0.6 on 2024-07-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('AL', 'Alagoas'), ('AP', 'Amapá'), ('MA', 'Maranhão'), ('GO', 'Goiás'), ('PA', 'Pará'), ('PI', 'Piauí'), ('RS', 'Rio Grande do Sul')], max_length=20, verbose_name='Distribuidora')),
                ('regionais', models.CharField(max_length=15, verbose_name='Regionais')),
            ],
        ),
        migrations.CreateModel(
            name='Comissionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('data_comissionamento', models.DateField()),
                ('distribuidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comissionamento.distribuidora')),
            ],
            options={
                'verbose_name': 'Comissionamento',
                'verbose_name_plural': 'Comissionamentos',
            },
        ),
    ]
