# Generated by Django 5.0.6 on 2024-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissionamento', '0002_distribuidora_comissionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Regional')),
                ('distribuidora', models.CharField(choices=[('AL', 'Alagoas'), ('AP', 'Amapá'), ('MA', 'Maranhão'), ('GO', 'Goiás'), ('PA', 'Pará'), ('PI', 'Piauí'), ('RS', 'Rio Grande do Sul')], max_length=20, verbose_name='Distribuidora')),
            ],
        ),
        migrations.AlterField(
            model_name='comissionamento',
            name='distribuidora',
            field=models.CharField(choices=[('AL', 'Alagoas'), ('AP', 'Amapá'), ('MA', 'Maranhão'), ('GO', 'Goiás'), ('PA', 'Pará'), ('PI', 'Piauí'), ('RS', 'Rio Grande do Sul')], max_length=20, verbose_name='Distribuidora'),
        ),
        migrations.DeleteModel(
            name='Distribuidora',
        ),
    ]
