# Generated by Django 5.0.6 on 2024-07-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissionamento', '0003_regional_alter_comissionamento_distribuidora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regional',
            options={'verbose_name': 'Regional', 'verbose_name_plural': 'Regionais'},
        ),
    ]
