# Generated by Django 5.0.6 on 2024-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissionamento', '0004_alter_regional_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissionamento',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
