# Generated by Django 5.0.6 on 2024-07-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissionamento', '0005_alter_comissionamento_data_solicitacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverAt',
        ),
    ]
