# Generated by Django 5.0.6 on 2024-07-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissionamento', '0006_delete_driverat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissionamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(max_length=255)),
                ('valor_novo', models.CharField(max_length=255)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('Comissionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='comissionamento.comissionamento')),
            ],
        ),
    ]
