# Generated by Django 5.0.6 on 2024-07-11 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissionamento', '0007_comissionamentohistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comissionamentohistorico',
            old_name='Comissionamento',
            new_name='comissionamento',
        ),
        migrations.AddField(
            model_name='comissionamentohistorico',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
